
====== IF ENTER_DT VIEWING FORMAT IS >ENTER_DT = '23-FEB-2015 06:56:39 PM'< ==========

SELECT TO_DATE(ENTER_DT, 'DD-MM-RRRR HH:MI:SS AM') MAXIMUM_DATE FROM CASH_DTL WHERE TO_DATE(ENTER_DT, 'DD-MM-RRRR HH:MI:SS AM')>SYSDATE-1;

SELECT TO_CHAR(TO_DATE(ENTER_DT, 'DD-MM-RRRR HH:MI:SS AM'), 'DD-MON-YYYY') FROM CUST_CREDIT_260116;

CREATE TABLE CUST_CREDIT_1 AS SELECT * FROM CUST_CREDIT;

ENTER_DT = '23-FEB-2015 06:56:39 PM'

DECLARE
CURSOR C1 IS
SELECT CUST_CODE, DAYS_LIMIT, AMOUNT_LIMIT, YEAR, TO_CHAR(TO_DATE(ENTER_DT, 'DD-MM-RRRR HH:MI:SS AM'), 'DD-MON-YYYY')ENTER_DT, EFF_DATE, CR_STAT, VALID_DT, DEPOT_CODE
FROM CUST_CREDIT_260116
WHERE EFF_DATE IS NULL;
BEGIN
FOR REC IN C1 LOOP
UPDATE CUST_CREDIT_260116
SET EFF_DATE=REC.ENTER_DT
WHERE EFF_DATE IS NULL
AND CUST_CODE=REC.CUST_CODE;
END LOOP;
COMMIT;
END;
/

====== IF ENTER_DT VIEWING FORMAT IS >ENTER_DT = '18-FEB-2016 16:08:40'< ========== FGS_OPL/FGS_OPL@TRNS



SELECT INVNO, INVDATE, ORD_NO, CHAL_NO, TO_CHAR(TO_DATE(ENTER_DT, 'DD-MM-RRRR HH24:MI:SS'), 'DD-MON-YYYY')ENTER_DT,DISP_STORE
FROM FGS_OPL.FGS_INVO_MAIN
WHERE INVNO IN (
'16-01754','16-01755','16-01745');

CREATE TABLE FGS_INVO_MAIN_1 AS SELECT * FROM FGS_OPL.FGS_INVO_MAIN WHERE INVNO IN (
'16-01754','16-01755','16-01745');;

DECLARE
CURSOR C1 IS
SELECT INVNO, INVDATE, ORD_NO, CHAL_NO, TO_CHAR(TO_DATE(ENTER_DT, 'DD-MM-RRRR HH24:MI:SS'), 'DD-MON-YYYY')ENTER_DT,DISP_STORE
FROM FGS_OPL.FGS_INVO_MAIN
WHERE INVNO IN (
'16-01754','16-01755','16-01745');
BEGIN
FOR REC IN C1 LOOP
UPDATE FGS_OPL.FGS_INVO_MAIN_1
SET EFF_DATE=REC.ENTER_DT
WHERE INVNO=REC.INVNO;
END LOOP;
END;
/

====== IF ENTER_DT VIEWING FORMAT IS >ENTER_DT = '19/08/2011 02:19:36 PM'< ==========

SELECT TO_CHAR(TO_DATE(ENTER_DT, 'DD/MM/RRRR HH:MI:SS AM'), 'DD-MON-YYYY HH:MI:SS AM') ENTER_DT FROM EMP;

SELECT A.DEPOT_CODE,A.SALECODE,A.EMPNO ,A.ENAME,B.EMPNO,B.DEPTNO,B.DESIG,C.DESIG_CODE,B.STATUS,B.LOC_CODE,B.FLOC_CODE FROM
(SELECT DEPOT_CODE,LOC_CODE, EMPNO,SALECODE,SUBSTR(ENAME,1,20)ENAME, DESIG_CODE, DEPTNO,EMP_STAT_CODE
FROM SMIS.EMP_TMP@CHQ)A,
(SELECT LOC_CODE,FLOC_CODE,EMPNO,DEPTNO,DESIG_CODE DESIG,SUBSTR(ENAME,1,20)ENAME,EMP_STAT_CODE STATUS, TO_CHAR(TO_DATE(ENTER_DT, 'DD/MM/RRRR HH:MI:SS AM'), 'DD-MON-YYYY HH:MI:SS AM') ENTER_DT
FROM EMP)B,
(SELECT DESIG_CODE FROM DESIG ORDER BY DESIG_CODE) C
WHERE A.EMPNO=B.EMPNO(+)
AND B.DESIG=C.DESIG_CODE(+)
AND A.DEPOT_CODE IN (SELECT DEPOT_CODE FROM SALESOFF)
ORDER BY A.DEPOT_CODE,A.EMPNO;

---- for month 


SELECT DISTINCT TO_DATE(ENTER_DT, 'DD-MM-RRRR') ENTER_DT FROM SMIS.ORDMAIN_WEB
WHERE TRUNC(ENTER_DT,'MON') BETWEEN (SELECT ADD_MONTHS(TRUNC(SYSDATE,'MON'),-10) FROM DUAL) AND (SELECT ADD_MONTHS(TRUNC(SYSDATE,'MON'),-0) FROM DUAL)
ORDER BY ENTER_DT DESC


